version: '3'
services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    container_name: 'movie-randomizer_frontend'
    env_file:
      - ./client/.env

  backend:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
    container_name: 'movie-randomizer_backend'
    env_file:
      - ./server/.env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: 'movie-randomizer_redis'
    volumes:
      - cache_data:/data

  postgres:
    image: postgres
    ports:
      - 5432:5432
    container_name: 'movie-randomizer_postgres'
    volumes:
      - movies_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env

volumes:
  cache_data:
  movies_data:
