version: '3'
services:
  frontend:
    build:
      context: ./client
      args:
        NODE_ENV: development
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  bot:
    build:
      context: ./bot
      args:
        NODE_ENV: development
    volumes:
      - ./bot:/bot
      - /bot/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
