version: "3"
services:
  frontend:
    build:
      context: ./client
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    command: npm start

  backend:
    build:
      context: ./server
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    command: npm run dev
